set -g mouse on
set -g status-style bg=black,fg=colour39
set -g status-right "%a, %d %b %Y %H:%M"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g window-status-current-style bg=black,fg=white,bold

# Window navigation with Alt+n (next) and Alt+p (previous)
bind-key -n M-n next-window
bind-key -n M-p previous-window
