local opts = { noremap = true, silent = true }
vim.keymap.set("n", "<C-s>", ":w<CR>", opts)
vim.keymap.set("n", "<C-w>", ":bd<CR>", opts)
vim.keymap.set("n", "<C-f>", ":Telescope live_grep <CR>", opts)
vim.keymap.set({ "n" }, "<F1>", ":Telescope find_files <CR>", opts)
vim.keymap.set({ "n" }, "<F2>", ":Neotree toggle <CR>", opts)
vim.keymap.set({ "n" }, "<F3>", ":Telescope buffers <CR>", opts)
vim.keymap.set("n", "<C-S>", function()
	require("conform").format({ lsp_fallback = true })
end, { desc = "Format file" })
